<?php

namespace AppBundle\Repository;

/**
 * MusicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicienRepository extends
    \Doctrine\ORM\EntityRepository
{
}
